export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_CHECK = "AUTH_CHECK";
export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_CONFIRM_REGISTER = "AUTH_CONFIRM_REGISTER";
export const AUTH_TAB_CHANGE = "AUTH_TAB_CHANGE";

export const ADMIN_LEDGER_SUCCESS = "ADMIN_ADD_LEDGER";
export const ADMIN_FAIL = "ADMIN_FAIL";
export const ADMIN_START = "ADMIN_START";
export const ADMIN_GET_LEDGER = "ADMIN_GET_LEDGER";

